import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Contact us page',
  description: 'Generated by create next app',
};

export default function ContactUsPage() {
  return <div>ContactUs page</div>;
}
