import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Grad and go page',
  description: 'Generated by create next app',
};

export default function GrabAndGoPage() {
  return <div>GrabAndGo page</div>;
}
