import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'In home executive delivery page',
  description: 'Generated by create next app',
};

export default function InHomeExecutiveDeliveryPage() {
  return <div>InHomeExecutiveDelivery page</div>;
}
