import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Catering and events page',
  description: 'Generated by create next app',
};

export default function CateringAndEventsPage() {
  return <div>CateringAndEvents page</div>;
}
