import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'About us page',
  description: 'Generated by create next app',
};

export default function AboutUsPage() {
  return <div>AboutUs page</div>;
}
